- name: install dependencies
  apt:
    pkg:
    - php7.2-fpm
    - php7.2-cli
    - php7.2-mysql
    - php7.2-json
    - php7.2-opcache
    - php7.2-mbstring
    - php7.2-xml
    - php7.2-gd
    - php7.2-curl
    - php-zip
    update_cache: yes

- name: restart php
  service:
    name: php7.2-fpm
    state: restarted
